# Testdata for postprocessing libraries.

package(
    default_visibility = [
        "//research/simulation/tensorflow/fluid:sim_research_fluid",
        "//third_party/py/swirl_lm:__subpackages__",
    ],
)

licenses(["notice"])

filegroup(
    name = "test_data",
    data = glob([
        "*.textpb",
    ]),
)
